### ISSUE TITLE
new publications

### ISSUE THREAD

**Issue by mohammadamint** [RAMP-project/ramp-website#4]
@FLomb I received this list of publications that can be added to website:

N. Stevanato, I. Sangiorgio, R. Mereu, E. Colombo, Archetypes of Rural Users in Sub-Saharan Africa for Load Demand Estimation, IEEE Power Africa (2023). https://doi.org/10.1109/PowerAfrica57932.2023.10363287

N. Stevanato et al., Guidelines for Demand Data Collection for Rural Access to Electricity Projects, IEEE Power Africa (2023). https://doi.org/10.1109/PowerAfrica57932.2023.10363265

N. Stevanato, R. Mereu, A. Brasco, A. Muumbo, A. Onori, E. Colombo, Access to Electricity in Informal Settlements: Literature Review and Load Curve Estimation, IEEE Power Africa (2023). https://doi.org/10.1109/PowerAfrica57932.2023.10363327

**Comment by FLomb** [comment]
Hi @mohammadamint, thanks!

It is also possible (for the next time) to just make a PR and ask to push them to the website. Anyhow, I think that two of them do use RAMP, but the second ('Guidelines etc.') does not. So I would only add the first and third; is that right?

**Comment by mohammadamint** [comment]
It seems so!

**Comment by FLomb** [comment]
Closed via a commit just now
